apiVersion: v1
kind: ConfigMap
metadata:
  name: example-nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      upstream rapidpro {
          # Proxy to Gunicorn socket and always retry, as recommended by deployment
          # guide: http://docs.gunicorn.org/en/stable/deploy.html
          server rapidpro:8000 max_fails=0;
      }
      upstream courier {
          server rapidpro-courier:8080 max_fails=0;
      }
      upstream mailroom {
          server rapidpro-mailroom:8090 max_fails=0;
      }
      server {
          # server_name example-rapidpro.org;
          listen 80;
          location ~ /c/ {
              proxy_set_header Host $http_host;
              proxy_pass http://courier;
              break;
          }
          location ~ /mr/ {
            proxy_set_header Host $http_host;
            proxy_pass http://mailroom;
            break;
          }
          location / {
              client_max_body_size 20m;
              proxy_pass http://rapidpro;
              proxy_set_header Host $http_host;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              # We only use the 'X-Forwarded-Proto' header from our load-balancer to
              # indicate the original connection used HTTPS, but Gunicorn by default
              # accepts more headers than that:
              # http://docs.gunicorn.org/en/19.7.1/settings.html#secure-scheme-headers
              # Overriding that config in Gunicorn is a bit complicated, and could
              # easily be overriden by accident by the user, so just delete those
              # other headers here so that a client can't set them
              # incorrectly/maliciously.
              proxy_set_header X-Forwarded-Proto "https";
              proxy_set_header X-Forwarded-Protocol "";
              proxy_set_header X-Forwarded-Ssl "";
          }
      }
    }
